USE [master]
GO

/****** Object:  Database [EmployeeDM]    Script Date: 2/26/2017 9:49:17 PM ******/
DROP DATABASE [EmployeeDM]
GO

/****** Object:  Database [EmployeeDM]    Script Date: 2/26/2017 9:49:17 PM ******/
CREATE DATABASE [EmployeeDM]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'EmployeeDM', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\EmployeeDM.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'EmployeeDM_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\DATA\EmployeeDM_log.ldf' , SIZE = 73728KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

ALTER DATABASE [EmployeeDM] SET COMPATIBILITY_LEVEL = 130
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [EmployeeDM].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [EmployeeDM] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [EmployeeDM] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [EmployeeDM] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [EmployeeDM] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [EmployeeDM] SET ARITHABORT OFF 
GO

ALTER DATABASE [EmployeeDM] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [EmployeeDM] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [EmployeeDM] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [EmployeeDM] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [EmployeeDM] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [EmployeeDM] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [EmployeeDM] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [EmployeeDM] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [EmployeeDM] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [EmployeeDM] SET  DISABLE_BROKER 
GO

ALTER DATABASE [EmployeeDM] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [EmployeeDM] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [EmployeeDM] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [EmployeeDM] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [EmployeeDM] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [EmployeeDM] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [EmployeeDM] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [EmployeeDM] SET RECOVERY FULL 
GO

ALTER DATABASE [EmployeeDM] SET  MULTI_USER 
GO

ALTER DATABASE [EmployeeDM] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [EmployeeDM] SET DB_CHAINING OFF 
GO

ALTER DATABASE [EmployeeDM] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [EmployeeDM] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [EmployeeDM] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [EmployeeDM] SET QUERY_STORE = OFF
GO

USE [EmployeeDM]
GO

ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = ON;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = PRIMARY;
GO

ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = OFF;
GO

ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = PRIMARY;
GO

ALTER DATABASE [EmployeeDM] SET  READ_WRITE 
GO

USE [EmployeeDM]
GO

/****** Object:  Table [dbo].[DIMDepartment]    Script Date: 2/26/2017 9:50:03 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[DIMDepartment](
	[DepartmentID] [smallint] NULL,
	[Name] [nvarchar](50) NULL
) ON [PRIMARY]

GO

USE [EmployeeDM]
GO

/****** Object:  Table [dbo].[EmployeeFact]    Script Date: 2/26/2017 9:50:36 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[EmployeeFact](
	[VacationHours] [smallint] NULL,
	[SickLeaveHours] [smallint] NULL,
	[BusinessEntityID] [int] NULL,
	[DepartmentID] [smallint] NULL,
	[Rate] [money] NULL,
	[Name] [nvarchar](50) NULL,
	[Male] [bit] NULL,
	[Female] [bit] NULL,
	[YearsWorked] [int] NULL,
	[Salaried] [bit] NULL,
	[Hourly] [bit] NULL
) ON [PRIMARY]

GO



